### PR TITLE
Pull threading approach from dwhjames aws-wrap library

### LINKED ISSUE #16: Something is spinning without terminating with S3StreamBuilder.uploadStreamAsFile
My stream is running, and completing, but then something is spinning for a minute after I shut down the ActorSystem before the process terminates. I'm not sure what is keeping the process alive, though.

### PR DESCRIPTION
**Pull request by joearasin**
Fixes #16

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
This seems pretty great! @dmnpignaud and @atamborrino any review here?

**Comment by malcolmgreaves** [comment]
@Timshel when you have a moment, I think this PR would be a great addition to the library =D !

**Comment by Timshel** [comment]
I'll check this next week, thank you.

**Comment by travis-mfglabs** [comment]
As answered in the issue, I don't believe any change are necessary.

**Pull request closed without merging**
